FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY /src/Awfq.Processos.Api/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY /src/Awfq.Processos.Api ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-focal
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Awfq.Processos.Api.dll"]